### ISSUE TITLE
An error can mask a warning

### ISSUE THREAD

**Issue by oalders** [skaji/syntax-check-perl#1]
@skaji thanks for all of your work on this.  I believe we will be crossing paths next week?

I've been meaning to test this out and finally got to it today.  I wanted to see how errors and warnings are handled and this is what I found. In the first case, we have a warning in the gutter:

![screen shot 2018-04-11 at 18 17 39](https://user-images.githubusercontent.com/96205/38646128-beb9aa24-3db4-11e8-9c71-16b797758b63.png)

However, if we add a line that introduces an error, our preceding warning is now also flagged as an error:

![screen shot 2018-04-11 at 18 17 54](https://user-images.githubusercontent.com/96205/38646120-b95021c6-3db4-11e8-8ad5-70e68872b76c.png)

**Comment by skaji** [comment]
@oalders thanks for testing this!

> I believe we will be crossing paths next week?

Yep, I'm looking forward to meeting you!

First, I want to say that:
* The current syntax-check-perl is far from perfect, but I'm willing to improve it.
* For example, currently syntax-check-perl does not try to distinguish warnings and errors

Let's discuss your issue.
I intentionally skip "redefined" warnings because it often happens. ([code](https://github.com/skaji/syntax-check-perl/blob/master/lib/Checker/Impl/Compile.pm#L16))
In fact, LWP::UserAgent emits "redefined" warnings:
```
❯ perl -wc lib/LWP/UserAgent.pm
Subroutine new redefined at lib/LWP/UserAgent.pm line 21.
Subroutine send_request redefined at lib/LWP/UserAgent.pm line 143.
...
```

So I don't think we have a warning in the gutter:
<img width="180" alt="screen shot 2018-04-12 at 8 17 57" src="https://user-images.githubusercontent.com/1589550/38647995-0911fb2e-3e2a-11e8-8e47-98c0b8494601.png">

**Comment by oalders** [comment]
Hi @skaji,

> Yep, I'm looking forward to meeting you!

Likewise!  I'm sure it'll be a fun few days.  :)

> I intentionally skip "redefined" warnings because it often happens.

It would be nice if that were configurable.  I do find those sorts of warnings to be quite helpful when I'm looking at $work code.  I can see how it's really noisy with `LWP::UserAgent`.  Do you know what's going on in that particular case?

I went back and checked this same case with the default `Ale` checking and it has the same problem.  If the compile was successful, it knows that any issues are warnings, but as soon as there's an error, it has no way of distinguishing errors from warnings.  @aaronpriven has a nice solution for this.  Basically, he has created a module called `MarkWarnings.pm` with the following contents:

```perl
$SIG{__WARN__} = sub { warn '=' , @_ };

1;
```

You can then invoke the checker with `-MMarkWarnings`.  There is then some really easy matching on lines to distinguish errors from warnings:

```
function! ale_linters#perl#perl#Handle(buffer, lines) abort
    let l:pattern = '\(.\+\) at \(.\+\) line \(\d\+\)'
    let l:output = []
    let l:basename = expand('#' . a:buffer . ':t')

    for l:match in ale#util#GetMatches(a:lines, l:pattern)
        let l:line = l:match[3]
        let l:text = l:match[1]

        if (0 == match(l:text, '=') )
          let l:type = 'W'
          let l:text = substitute(l:text, "^=" , "", "")
        else
          let l:type = 'E'
        endif

        if ale#path#IsBufferPath(a:buffer, l:match[2])
        \ && (
        \   l:text isnot# 'BEGIN failed--compilation aborted'
        \   || empty(l:output)
        \   || match(l:output[-1].text, s:begin_failed_skip_pattern) < 0
        \ )
            call add(l:output, {
            \   'lnum': l:line,
            \   'text': l:text,
            \   'type': l:type,
            \})
        endif
    endfor

    return l:output
endfunction
```

This is from Aaron's fork of `perl.vim` in `Ale`.  Perhaps this approach would be helpful to you?

**Comment by skaji** [comment]
@oalders thanks for suggestion!
I'm working on https://github.com/skaji/syntax-check-perl/tree/wip branch, where I finally create a custom linter `syntax_check` for ale.
I hope I finish this during PTS:)

**Comment by skaji** [comment]
@oalders 
I really appreciate your feedback and suggestion! And now...

* I ended up creating a new linter `syntax_check`.
* It distinguishes errors from warnings.
  <img width="279" alt="screen shot 2018-04-22 at 7 03 06" src="https://user-images.githubusercontent.com/1589550/39091723-8ac5eed6-45fb-11e8-8d60-d72768f7f0c6.png">
* It does not skip `redefined` warnings, etc, by default.
* OTOH, it is configured by setting `g:ale_perl_syntax_check_config` in vimrc.

Please look at README.md in https://github.com/skaji/syntax-check-perl

I close this issue.

**Comment by skaji** [comment]
By the way, I received an email from w0rp (the author of ale),
and he/she said: How about creating PR for ale to add syntax-check-perl.
Wow, he/she is very kind!

**Comment by oalders** [comment]
@skaji thanks so much for this.  I will test this out at $work this week.  🎆 

> By the way, I received an email from w0rp (the author of ale),
and he/she said: How about creating PR for ale to add syntax-check-perl.
Wow, he/she is very kind!

I've had very good experiences with the author of Ale.  I'd encourage you to create a PR for it once you feel the code is ready.  👍
